<template>
  <div class="metroviz-canvas w-full overflow-x-auto">
    <div :id="containerId" style="min-height: 600px;"></div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, watch, getCurrentInstance, nextTick } from 'vue'
import type { MetrovizInputData } from '@/composables/useMetrovizData'

// Vendor imports — these are ES6 modules, imported at component scope
// Metroviz uses D3 internally; must run client-side only (onMounted)
let MetroRenderer: any = null
let LayoutEngine: any = null
let DataModel: any = null

const props = defineProps<{
  data: MetrovizInputData
  sourceTitle?: string
}>()

const emit = defineEmits<{
  'node-click': [pageId: string | null]
}>()

// Unique ID per instance to avoid CSS selector collisions
const instanceId = getCurrentInstance()?.uid ?? Math.random().toString(36).slice(2)
const containerId = `metroviz-container-${instanceId}`

let rendererInstance: any = null
let isInitialized = false
let clickListenerAttached = false

function attachClickListener() {
  const container = document.getElementById(containerId)
  if (!container || clickListenerAttached) return
  container.addEventListener('click', (e: Event) => {
    const target = e.target as Element
    const stationEl = target.closest('[data-id]') as Element | null
    if (stationEl) {
      const pageId = stationEl.getAttribute('data-id')
      emit('node-click', pageId)
    } else {
      emit('node-click', null)
    }
  })
  clickListenerAttached = true
}

async function loadLibraries() {
  if (isInitialized) return
  // Metroviz vendor files reference d3 as a global — expose it before importing them
  const d3 = await import('d3')
  ;(window as any).d3 = d3
  // Dynamic imports to ensure these only run in browser context (not SSR)
  const [rendererMod, layoutMod, dataMod] = await Promise.all([
    import('@/vendor/metroviz/js/metro-renderer.js'),
    import('@/vendor/metroviz/js/layout-engine.js'),
    import('@/vendor/metroviz/js/data-model.js'),
  ])
  MetroRenderer = rendererMod.MetroRenderer
  LayoutEngine = layoutMod.LayoutEngine
  DataModel = dataMod.DataModel
  isInitialized = true
}

async function renderMap(data: MetrovizInputData) {
  await loadLibraries()

  const container = document.getElementById(containerId)
  if (!container) return

  // D-03: Destroy previous render before re-initializing
  container.innerHTML = ''
  rendererInstance = null

  try {
    const dataModel = new DataModel()
    const normalizedData = dataModel.validateAndNormalize(data)

    const layoutEngine = new LayoutEngine()
    const layout = layoutEngine.calculate(normalizedData)

    // MetroRenderer takes a CSS selector string
    rendererInstance = new MetroRenderer(`#${containerId}`)
    rendererInstance.render(layout)
    await nextTick()
    attachClickListener()
  } catch (err) {
    console.error('[MetrovizMap] Render error:', err)
    container.innerHTML = `<div class="p-4 text-red-600">Metro map could not be rendered: ${err instanceof Error ? err.message : 'Unknown error'}</div>`
  }
}

onMounted(() => {
  renderMap(props.data)
})

// D-03: Re-initialize on data changes (no reactive updates — full re-init)
watch(
  () => props.data,
  (newData) => renderMap(newData),
  { deep: true }
)

onBeforeUnmount(() => {
  const container = document.getElementById(containerId)
  if (container) container.innerHTML = ''
  rendererInstance = null
})

defineExpose({ containerId })
</script>

<style scoped>
.metroviz-canvas {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 4px;
  padding: 4px;
}
</style>

<style>
/* Import Metroviz styles globally (not scoped — affects SVG generated by the library) */
@import '@/vendor/metroviz/css/metroviz.css';
</style>
