<template>
  <div class="metroviz-canvas w-full" :class="{ 'hide-timeline-axis': showTimeline === false }">
    <div :id="containerId" style="height: 100%;"></div>
    <div class="zoom-hint">⌃ Ctrl + scroll to zoom · drag to pan</div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, watch, getCurrentInstance, nextTick } from 'vue'
import type { MetrovizInputData } from '@/composables/useMetrovizData'

// Vendor imports — these are ES6 modules, imported at component scope
// Metroviz uses D3 internally; must run client-side only (onMounted)
let MetroRenderer: any = null
let LayoutEngine: any = null
let DataModel: any = null

const props = defineProps<{
  data: MetrovizInputData
  sourceTitle?: string
  showTimeline?: boolean
}>()

const emit = defineEmits<{
  'node-click': [pageId: string | null]
}>()

// Unique ID per instance to avoid CSS selector collisions
const instanceId = getCurrentInstance()?.uid ?? Math.random().toString(36).slice(2)
const containerId = `metroviz-container-${instanceId}`

let rendererInstance: any = null
let isInitialized = false
let clickListenerAttached = false

function attachClickListener() {
  const container = document.getElementById(containerId)
  if (!container || clickListenerAttached) return
  container.addEventListener('click', (e: Event) => {
    const target = e.target as Element
    const stationEl = target.closest('[data-id]') as Element | null
    if (stationEl) {
      const pageId = stationEl.getAttribute('data-id')
      emit('node-click', pageId)
    } else {
      emit('node-click', null)
    }
  })
  clickListenerAttached = true
}

async function loadLibraries() {
  if (isInitialized) return
  // Metroviz vendor files reference d3 as a global — expose it before importing them
  const d3 = await import('d3')
  ;(window as any).d3 = d3
  // Metroviz uses i18next for tooltip labels; provide a pass-through stub if not already loaded
  if (!(window as any).i18next) {
    ;(window as any).i18next = {
      t: (key: string, opts?: any) => opts?.defaultValue ?? key,
      language: 'en',
    }
  }
  // Dynamic imports to ensure these only run in browser context (not SSR)
  const [rendererMod, layoutMod, dataMod] = await Promise.all([
    import('@/vendor/metroviz/js/metro-renderer.js'),
    import('@/vendor/metroviz/js/layout-engine.js'),
    import('@/vendor/metroviz/js/data-model.js'),
  ])
  MetroRenderer = rendererMod.MetroRenderer
  LayoutEngine = layoutMod.LayoutEngine
  DataModel = dataMod.DataModel
  isInitialized = true
}

async function renderMap(data: MetrovizInputData) {
  await loadLibraries()

  const container = document.getElementById(containerId)
  if (!container) return

  // D-03: Destroy previous render before re-initializing
  container.innerHTML = ''
  rendererInstance = null

  try {
    const dataModel = new DataModel()
    const normalizedData = dataModel.validateAndNormalize(data)

    const layoutEngine = new LayoutEngine()
    const layout = layoutEngine.calculate(normalizedData)

    // MetroRenderer takes a CSS selector string
    rendererInstance = new MetroRenderer(`#${containerId}`)
    rendererInstance.render(layout)
    await nextTick()
    attachClickListener()
  } catch (err) {
    console.error('[MetrovizMap] Render error:', err)
    container.innerHTML = `<div class="p-4 text-red-600">Metro map could not be rendered: ${err instanceof Error ? err.message : 'Unknown error'}</div>`
  }
}

onMounted(() => {
  renderMap(props.data)
})

// Re-render on any data reference change. metrovizData (the parent computed) always
// returns a new object, so reference equality is sufficient — and more reliable than
// deep comparison, which can suppress renders when content appears structurally equal.
watch(() => props.data, (newData) => renderMap(newData))

onBeforeUnmount(() => {
  const container = document.getElementById(containerId)
  if (container) container.innerHTML = ''
  rendererInstance = null
})

defineExpose({ containerId })
</script>

<style scoped>
.metroviz-canvas {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 4px;
  padding: 4px;
  max-height: 70vh;
  overflow: hidden;
  position: relative;
}
.zoom-hint {
  position: absolute;
  bottom: 8px;
  left: 0;
  right: 0;
  text-align: center;
  font-size: 11px;
  color: #9ca3af;
  pointer-events: none;
  user-select: none;
}
</style>

<style>
/* Import Metroviz styles globally (not scoped — affects SVG generated by the library) */
@import '@/vendor/metroviz/css/metroviz.css';

/* Make year/quarter labels more readable (Metroviz defaults: 15px #555 years, 7px #999 quarters) */
.axis-grid-years text {
  font-size: 13px !important;
  fill: #374151 !important;
  font-weight: 600 !important;
}
.axis-grid-quarters text {
  font-size: 10px !important;
  fill: #6b7280 !important;
}

.hide-timeline-axis .axis {
  display: none !important;
}
</style>
